name: bump-and-publish
author: openbible-io
inputs:
  NPM_TOKEN:
    required: true
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4 # Replace once `bun publish` supports provenance
      with:
        registry-url: https://registry.npmjs.org
    - run: ${{ github.action_path }}/bump-and-publish.sh
      shell: bash
      env:
        NODE_AUTH_TOKEN: ${{ inputs.NPM_TOKEN }}
