name: 'bump-and-publish'
description: 'Bumps version (or uses manual tag) and runs `deno publish`'
author: 'openbible-io'
inputs:
  NPM_TOKEN:
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4 # `bun publish` doesn't yet support provenance
      with:
        registry-url: 'https://registry.npmjs.org'
    - run: ${{ github.action_path }}/bump-and-publish.sh
      shell: bash
      env:
        NODE_AUTH_TOKEN: ${{ inputs.NPM_TOKEN }}
