name: 'bump-and-publish'
description: 'Bumps version (or uses manual tag) and runs `deno publish`'
author: 'openbible-io'
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/bump-and-publish.sh
      shell: bash
